### ISSUE TITLE
dtf drops .dtflog all over and expects to write to it

### ISSUE THREAD

**Issue by jakev** [jakev/dtf#15]
Due to changes in src/dtf/logging.py, dtf attempts to create a log file everytime the file is sourced.  This fails if it unable to write to the file, such as the following example:
```
Traceback (most recent call last):
  File "/usr/local/bin/dtf", line 34, in <module>
    import dtf.packages as pkg
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 18, in <module>
    import dtf.core.packagemanager as pm
  File "/usr/local/lib/python2.7/dist-packages/dtf/core/packagemanager.py", line 19, in <module>
    import dtf.logging as log
  File "/usr/local/lib/python2.7/dist-packages/dtf/logging.py", line 38, in <module>
    LOG_FILE = open(LOG_FILE_NAME, 'a')
IOError: [Errno 13] Permission denied: '.dtflog'
bash: .: filename argument required
.: usage: . filename [arguments]
```

The only time a log file should be created is if dtf detects a project directory.

**Comment by jakev** [comment]
Fixed @https://github.com/jakev/dtf/commit/da4f529c9a1325119d42d55c75c2671ff356f701
