### ISSUE TITLE
`dtf status` ValueError

### ISSUE THREAD

**Issue by jakev** [jakev/dtf#17]
```
12:06:10 /DevTesting/test$ dtf status
Traceback (most recent call last):
  File "/usr/local/bin/dtf", line 185, in <module>
    sys.exit(main())
  File "/usr/local/bin/dtf", line 169, in main
    rtn = pkg.launch_builtin_module(command_name, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 124, in launch_builtin_module
    return __launch_python_module(launch_path, cmd, args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 79, in __launch_python_module
    return mod_inst.run(args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/module.py", line 62, in run
    result = getattr(self, 'execute')(args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/core/cmds/status.py", line 35, in execute
    devices = self.adb.get_devices()
  File "/usr/local/lib/python2.7/dist-packages/dtf/adb.py", line 107, in get_devices
    serial, device_type = device.split('\t')
ValueError: need more than 1 value to unpack```

**Comment by jakev** [comment]
fixed: https://github.com/jakev/dtf/commit/4f493d2fb2acbf625601713d7aa1d74696bbe81d
