### ISSUE TITLE
Non-existent import failure

### ISSUE THREAD

**Issue by jakev** [jakev/dtf#19]
```
07:54:43 /DevTesting$ echo "import garbage" > testing
08:24:20 /DevTesting$ dtf pm install --single module --name testing --auto
[Sat Nov 07 20:24:34 EST 2015] pm/I - Attempting to auto parse... 
Traceback (most recent call last):
  File "/usr/local/bin/dtf", line 185, in <module>
    sys.exit(main())
  File "/usr/local/bin/dtf", line 149, in main
    return pkg.launch_builtin_module('pm', sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 124, in launch_builtin_module
    return __launch_python_module(launch_path, cmd, args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 79, in __launch_python_module
    return mod_inst.run(args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/module.py", line 62, in run
    result = getattr(self, 'execute')(args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/core/cmds/pm.py", line 719, in execute
    rtn = self.do_install(args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/core/cmds/pm.py", line 136, in do_install
    item = self.auto_parse_module(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/core/cmds/pm.py", line 587, in auto_parse_module
    if packagemanager.is_python_module(local_name, install_name):
  File "/usr/local/lib/python2.7/dist-packages/dtf/core/packagemanager.py", line 336, in is_python_module
    imp.load_source(name, module_path)
  File "testing", line 1, in <module>
    import garbage
ImportError: No module named garbage
```

**Comment by jakev** [comment]
Fixed: https://github.com/jakev/dtf/commit/cb6b19aef7e820b202d0573ef2db7095deaacec2
