### ISSUE TITLE
Launching bash module from non TOP directory fails

### ISSUE THREAD

**Issue by jakev** [jakev/dtf#21]
example:

```
04:15:55 /DevTesting/Fire/.drozer$ dtf usesperm
Traceback (most recent call last):
  File "/usr/local/bin/dtf", line 185, in <module>
    sys.exit(main())
  File "/usr/local/bin/dtf", line 175, in main
    rtn = pkg.launch_module(command_name, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 180, in launch_module
    return __launch_bash_module(module_path, args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 112, in __launch_bash_module
    serial = prop.get_prop('Info', 'serial')
  File "/usr/local/lib/python2.7/dist-packages/dtf/properties.py", line 62, in get_prop
    raise PropertyError(err)
dtf.properties.PropertyError: Property section not found: Info
```

**Comment by jakev** [comment]
Fixed: https://github.com/jakev/dtf/commit/ec66bd36ba98cb19e3d17768b47f4093849cb8ae
