### ISSUE TITLE
Export fails when modules lack version

### ISSUE THREAD

**Issue by jakev** [jakev/dtf#22]
```
06:38:58 /DevTesting$ dtf pm export test.zip
Traceback (most recent call last):
  File "/usr/local/bin/dtf", line 185, in <module>
    sys.exit(main())
  File "/usr/local/bin/dtf", line 149, in main
    return pkg.launch_builtin_module('pm', sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 145, in launch_builtin_module
    return __launch_python_module(launch_path, cmd, args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 97, in __launch_python_module
    return mod_inst.run(args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/module.py", line 62, in run
    result = getattr(self, 'execute')(args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/core/cmds/pm.py", line 723, in execute
    rtn = self.do_export(args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/core/cmds/pm.py", line 235, in do_export
    rtn = self.generate_export_xml(export_items, export_manifest)
  File "/usr/local/lib/python2.7/dist-packages/dtf/core/cmds/pm.py", line 390, in generate_export_xml
    item_xml.attrib['majorVersion'] = item.major_version
  File "lxml.etree.pyx", line 2245, in lxml.etree._Attrib.__setitem__ (src/lxml/lxml.etree.c:58775)
  File "apihelpers.pxi", line 547, in lxml.etree._setAttributeValue (src/lxml/lxml.etree.c:19025)
  File "apihelpers.pxi", line 1393, in lxml.etree._utf8 (src/lxml/lxml.etree.c:26460)
TypeError: Argument must be bytes or unicode, got 'NoneType'
```

**Comment by jakev** [comment]
Forgot to close this: https://github.com/jakev/dtf/commit/439a2bcf80b93bbc18b802bdbf6a2b408640cea0
